//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.LittleFashion_Kentico13;

[assembly: RegisterDocumentType(ContactForm.CLASS_NAME, typeof(ContactForm))]

namespace CMS.DocumentEngine.Types.LittleFashion_Kentico13
{
	/// <summary>
	/// Represents a content item of type ContactForm.
	/// </summary>
	public partial class ContactForm : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "LittleFashion_Kentico13.ContactForm";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactForm fields.
		/// </summary>
		private readonly ContactFormFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ContactFormID.
		/// </summary>
		[DatabaseIDField]
		public int ContactFormID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ContactFormID"), 0);
			}
			set
			{
				SetValue("ContactFormID", value);
			}
		}


		/// <summary>
		/// FormTitle.
		/// </summary>
		[DatabaseField]
		public string FormTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FormTitle"), @"");
			}
			set
			{
				SetValue("FormTitle", value);
			}
		}


		/// <summary>
		/// Button.
		/// </summary>
		[DatabaseField]
		public string Button
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Button"), @"");
			}
			set
			{
				SetValue("Button", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactForm fields.
		/// </summary>
		[RegisterProperty]
		public ContactFormFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactForm fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactFormFields : AbstractHierarchicalObject<ContactFormFields>
		{
			/// <summary>
			/// The content item of type ContactForm that is a target of the extended API.
			/// </summary>
			private readonly ContactForm mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactFormFields" /> class with the specified content item of type ContactForm.
			/// </summary>
			/// <param name="instance">The content item of type ContactForm that is a target of the extended API.</param>
			public ContactFormFields(ContactForm instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ContactFormID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ContactFormID;
				}
				set
				{
					mInstance.ContactFormID = value;
				}
			}


			/// <summary>
			/// FormTitle.
			/// </summary>
			public string FormTitle
			{
				get
				{
					return mInstance.FormTitle;
				}
				set
				{
					mInstance.FormTitle = value;
				}
			}


			/// <summary>
			/// Button.
			/// </summary>
			public string Button
			{
				get
				{
					return mInstance.Button;
				}
				set
				{
					mInstance.Button = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactForm" /> class.
		/// </summary>
		public ContactForm() : base(CLASS_NAME)
		{
			mFields = new ContactFormFields(this);
		}

		#endregion
	}
}