//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.LittleFashion_Kentico13;

[assembly: RegisterDocumentType(Test.CLASS_NAME, typeof(Test))]

namespace CMS.DocumentEngine.Types.LittleFashion_Kentico13
{
	/// <summary>
	/// Represents a content item of type Test.
	/// </summary>
	public partial class Test : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "LittleFashion_Kentico13.Test";


		/// <summary>
		/// The instance of the class that provides extended API for working with Test fields.
		/// </summary>
		private readonly TestFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with Test fields.
		/// </summary>
		[RegisterProperty]
		public TestFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Test fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TestFields : AbstractHierarchicalObject<TestFields>
		{
			/// <summary>
			/// The content item of type Test that is a target of the extended API.
			/// </summary>
			private readonly Test mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TestFields" /> class with the specified content item of type Test.
			/// </summary>
			/// <param name="instance">The content item of type Test that is a target of the extended API.</param>
			public TestFields(Test instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Test" /> class.
		/// </summary>
		public Test() : base(CLASS_NAME)
		{
			mFields = new TestFields(this);
		}

		#endregion
	}
}