//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.LittleFashion_Kentico13;

[assembly: RegisterDocumentType(Temp.CLASS_NAME, typeof(Temp))]

namespace CMS.DocumentEngine.Types.LittleFashion_Kentico13
{
	/// <summary>
	/// Represents a content item of type Temp.
	/// </summary>
	public partial class Temp : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "LittleFashion_Kentico13.Temp";


		/// <summary>
		/// The instance of the class that provides extended API for working with Temp fields.
		/// </summary>
		private readonly TempFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TempID.
		/// </summary>
		[DatabaseIDField]
		public int TempID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TempID"), 0);
			}
			set
			{
				SetValue("TempID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Temp fields.
		/// </summary>
		[RegisterProperty]
		public TempFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Temp fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TempFields : AbstractHierarchicalObject<TempFields>
		{
			/// <summary>
			/// The content item of type Temp that is a target of the extended API.
			/// </summary>
			private readonly Temp mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TempFields" /> class with the specified content item of type Temp.
			/// </summary>
			/// <param name="instance">The content item of type Temp that is a target of the extended API.</param>
			public TempFields(Temp instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TempID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TempID;
				}
				set
				{
					mInstance.TempID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Temp" /> class.
		/// </summary>
		public Temp() : base(CLASS_NAME)
		{
			mFields = new TempFields(this);
		}

		#endregion
	}
}