//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.LittleFashion_Kentico13;

[assembly: RegisterDocumentType(Footer.CLASS_NAME, typeof(Footer))]

namespace CMS.DocumentEngine.Types.LittleFashion_Kentico13
{
	/// <summary>
	/// Represents a content item of type Footer.
	/// </summary>
	public partial class Footer : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "LittleFashion_Kentico13.Footer";


		/// <summary>
		/// The instance of the class that provides extended API for working with Footer fields.
		/// </summary>
		private readonly FooterFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FooterID.
		/// </summary>
		[DatabaseIDField]
		public int FooterID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FooterID"), 0);
			}
			set
			{
				SetValue("FooterID", value);
			}
		}


		/// <summary>
		/// CopyRight Text.
		/// </summary>
		[DatabaseField]
		public string CopyRightText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CopyRightText"), @"");
			}
			set
			{
				SetValue("CopyRightText", value);
			}
		}


		/// <summary>
		/// Sitemap Text.
		/// </summary>
		[DatabaseField]
		public string SitemapText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SitemapText"), @"");
			}
			set
			{
				SetValue("SitemapText", value);
			}
		}


		/// <summary>
		/// Social Text.
		/// </summary>
		[DatabaseField]
		public string SocialText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SocialText"), @"");
			}
			set
			{
				SetValue("SocialText", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Footer fields.
		/// </summary>
		[RegisterProperty]
		public FooterFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Footer fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FooterFields : AbstractHierarchicalObject<FooterFields>
		{
			/// <summary>
			/// The content item of type Footer that is a target of the extended API.
			/// </summary>
			private readonly Footer mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FooterFields" /> class with the specified content item of type Footer.
			/// </summary>
			/// <param name="instance">The content item of type Footer that is a target of the extended API.</param>
			public FooterFields(Footer instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FooterID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.FooterID;
				}
				set
				{
					mInstance.FooterID = value;
				}
			}


			/// <summary>
			/// CopyRight Text.
			/// </summary>
			public string CopyRightText
			{
				get
				{
					return mInstance.CopyRightText;
				}
				set
				{
					mInstance.CopyRightText = value;
				}
			}


			/// <summary>
			/// Sitemap Text.
			/// </summary>
			public string SitemapText
			{
				get
				{
					return mInstance.SitemapText;
				}
				set
				{
					mInstance.SitemapText = value;
				}
			}


			/// <summary>
			/// Social Text.
			/// </summary>
			public string SocialText
			{
				get
				{
					return mInstance.SocialText;
				}
				set
				{
					mInstance.SocialText = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Footer" /> class.
		/// </summary>
		public Footer() : base(CLASS_NAME)
		{
			mFields = new FooterFields(this);
		}

		#endregion
	}
}